name       : haskell-path-pieces
version    : 0.2.1
release    : 1
source     :
    - http://hackage.haskell.org/package/path-pieces-0.2.1/path-pieces-0.2.1.tar.gz : 080bd49f53e20597ca3e5962e0c279a3422345f5b088840a30a751cd76d4a36f
license    : BSD-3-Clause
component  : programming.haskell
summary    : Defines two typeclasses used for converting Haskell data types to and from route pieces. Used in Yesod to automatically marshall data in the request path.
description: |
    Defines two typeclasses used for converting Haskell data types to and from route pieces. Used in Yesod to automatically marshall data in the request path.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
